---
name: Compile C Project

on:
  workflow_call: {}  # Allows this workflow to be called by other workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Install dependencies (if needed)
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y build-essential

    # Compile the C project
    - name: Compile C project
      run: |
        gcc $(find . -name "*.c")  # Compiles all .c files, output will be a.out by default
        ls -lah  # List the compiled files to verify

    # Save compiled binary as artifact
    - name: Save binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binary
        path: ./a.out  # a.out is the default binary name after compilation
        retention-days: 3
