---
name: Compile C Project

on:
  push: null

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Install dependencies (if needed)
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y build-essential

    - name: Compile C project
      run: |
        gcc *.c
        ls -lah
