---
name: Valgrind Test

on:
  push: null

jobs:
  use-artifact:
    uses: Vianpyro/Valgrind/.github/workflows/gcc.yml@main  # Move the reusable workflow reference to the jobs level

  run-binary:
    runs-on: ubuntu-latest

    needs: use-artifact  # This job depends on the previous one

    steps:
      # Download the compiled binary artifact
      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: compiled-binary
          path: ./  # Download to the current directory

      # Run the binary
      - name: Run the binary
        run: ./a.out
