---
name: Valgrind Test

on:
  push: null

jobs:
  use-artifact:
    runs-on: ubuntu-latest

    steps:
    # Call the reusable workflow
    - name: Compile the C project
      uses: Vianpyro/Valgrind/.github/workflows/gcc.yml@main  # Reference the reusable workflow

    # Download the compiled binary artifact
    - name: Download compiled binary
      uses: actions/download-artifact@v4
      with:
        name: compiled-binary
        path: ./  # Download to the current directory

    # Run the binary
    - name: Run the binary
      run: ./a.out
