---
name: Valgrind Test

on:
  push: null

jobs:
  use-artifact:
    uses: Vianpyro/Valgrind/.github/workflows/gcc.yml@main

  run-binary:
    runs-on: ubuntu-latest
    needs: use-artifact

    steps:
      # Download the compiled binary artifact
      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: compiled-binary
          path: ./  # Download to the current directory

      # Make the binary executable
      - name: Make the binary executable
        run: chmod +x ./a.out

      # Install Valgrind
      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      # Run the binary with Valgrind
      - name: Run Valgrind
        run: valgrind --leak-check=full --track-origins=yes --show-reachable=yes ./a.out
