---
name: Valgrind Workflow

on:
  workflow_call:  # Makes this workflow reusable by other repositories

jobs:
  run-valgrind:
    name: Run Valgrind on the C binary
    runs-on: ubuntu-latest

    steps:
      # Download the compiled binary artifact
      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: compiled-binary
          path: ./  # Download to the current directory

      # Make the binary executable
      - name: Make the binary executable
        run: chmod +x ./a.out

      # Install Valgrind
      - name: Install Valgrind
        run: sudo apt update && sudo apt install -y valgrind

      # Run Valgrind to check for memory leaks
      - name: Run Valgrind
        run: |
          chmod +x ./a.out  # Make sure binary is executable
          valgrind --leak-check=full \
                   --track-origins=yes \
                   --show-reachable=yes \
                   --error-exitcode=1 \
                   ./a.out
