---
name: Valgrind Workflow

on:
  workflow_call:  # Makes this workflow reusable by other repositories

jobs:
  run-valgrind:
    name: Run Valgrind on the C binary
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Compile the project (this could be customized)
      - name: Compile project
        run: gcc *.c

      # Install Valgrind
      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      # Run Valgrind to check for memory leaks
      - name: Run Valgrind
        run: |
          chmod +x ./a.out  # Make sure binary is executable
          valgrind --leak-check=full \
                   --track-origins=yes \
                   --show-reachable=yes \
                   --error-exitcode=1 \
                   ./a.out
