---
name: Valgrind Test

on:
  workflow_run:
    workflows: ["Compile C Project"]
    types:
      - completed

jobs:
  valgrind:
    runs-on: ubuntu-latest

    steps:
    # Download the compiled binary artifact
    - name: Download compiled binary
      uses: actions/download-artifact@v4.1.8
      with:
        name: compiled-binary
        path: ./ # Download to current directory

    # Install Valgrind
    - name: Install Valgrind
      run: sudo apt install -y valgrind

    # Run Valgrind to check memory issues
    - name: Run Valgrind
      run: |
        valgrind --leak-check=full ./a.out
