---
name: Valgrind Test

on:
  push: null

jobs:
  create-artifact:
    name: Create Artifact
    uses: Vianpyro/Valgrind/.github/workflows/gcc.yml@main

  test-memory-leaks:
    name: Test Memory Leaks with Valgrind
    runs-on: ubuntu-latest
    needs: create-artifact

    steps:
      # Download the compiled binary artifact
      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: compiled-binary
          path: ./  # Download to the current directory

      # Make the binary executable
      - name: Make the binary executable
        run: chmod +x ./a.out

      # Install Valgrind
      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      # Run the binary with Valgrind and fail on memory leaks
      - name: Run Valgrind
        run: |
          valgrind --leak-check=full \
                   --track-origins=yes \
                   --show-reachable=yes \
                   --error-exitcode=1 \
                   ./a.out
